/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package global.coda.hopsitalmanagement.svc;

import static org.testng.AssertJUnit.assertNotNull;

import java.util.ArrayList;
import java.util.List;

import org.testng.annotations.Test;


import static org.testng.Assert.assertEquals;
import static org.testng.Assert.fail;

import org.apache.log4j.BasicConfigurator;
import org.apache.log4j.Logger;
import global.coda.patientdetails.model.Patient;
import global.coda.hopsitalmanagement.svc.PatientServices;

public class CreatePatientsTest {
	   @Test public void testCreatepatients() {
	    	Logger logger = Logger.getLogger(CreatePatientsTest.class);
	    	BasicConfigurator.configure();

	    	try {
	    		int age= 19;
	    		String name= "Lingesh";
	    		List<String> address =  new ArrayList<>();
	    		address.add("a");
	    		address.add("b");
	    		address.add("c");
//
//	    		String myReturnedObject=PatientServices.create(id,age,name,address).toString();
//	    		String Result = "Patient [age=19, name=Lingesh, address=[a, b, c]]";
//	    		 assertNotNull(myReturnedObject);
//	    	        assertEquals( Result, myReturnedObject);

	    		
	    	}
	    	catch(Exception e){
	            fail("got Exception, i want an Expression");

	    		
	    	}

	   
	    }
	   @Test public void testReadpatients() {
	    
	    	try {
//	    		String myReturnedObject=CrudOperations.read(Map).toString();
//	    		 assertNotNull(myReturnedObject);
//	    	        assertEquals(true, myReturnedObject);
	    		
	    	}
	    	catch(Exception e){
	            fail("got Exception, i want an Expression");

	    		
	    	}

	   
	    }
}
